version: "3.9"

services:
  app:
    build: ./app
    container_name: diet_app
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - /home/bluemusk/diet-assistant/lancedb:/app/lancedb 
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=diet_db

  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: diet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana_datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
    depends_on:
      - db

volumes:
  postgres_data:
  grafana_data:
