FROM python:3.10.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

COPY ["diet-feedback.py",  "./"]

#COPY ["Introduction to Nutrition Science, LibreTexts Project.pdf", "./"]

RUN mkdir -p /app/lancedb

EXPOSE 8501

CMD ["streamlit", "run", "diet-feedback.py", "--server.port=8501", "--server.address=0.0.0.0"]
