apiVersion: 1

datasources:
  - name: NewPostgreSQL
    type: postgres
    access: proxy
    url: postgres_db:5432
    user: postgres
    password: yourpassword
    database: diet_db
    jsonData:
      sslmode: disable
